### ISSUE TITLE
Auth is not working for me

### ISSUE THREAD

**Issue by Monstrofil** [Geoalert/mapflow-docs-ru#12]
Hello, 

I'm getting this when trying to auth using mapflow.ai credentials:
```
{
"code": "AUTHENTICATION_ERROR",
"message": "Wrong login/password."
}
```

As login I'm using my email from mapflow.ai. Does that api still work?

**Comment by Godnik** [comment]
Contact us at hello@geoalert.io  - as for now we have to activate user account to work with API. Now it's dedicated only for enterprise users.
